learning_rate : 0.0001
max_steps : 50
batch_size : 32
eval_freq : 500
data_dir : ./cifar10/cifar-10-batches-py
--------------Convnet initialized------------
(10000, 3, 32, 32)
-----------------------
test accuracy: 0.10000000000000002
-----------------------
-----------------------
test accuracy: 0.2531
-----------------------
-----------------------
test accuracy: 0.3509
-----------------------
-----------------------
test accuracy: 0.3435
-----------------------
epoch 1 avg accuracy on training data: 0.2803502879078695
Traceback (most recent call last):
  File "train_convnet_pytorch.py", line 215, in <module>
    main()
  File "train_convnet_pytorch.py", line 198, in main
    train()
  File "train_convnet_pytorch.py", line 137, in train
    test_acc, test_loss = calculateTest(X_test, test_labels, 20, cnn, criterion, test_labels_onehot=Y_test)
  File "train_convnet_pytorch.py", line 46, in calculateTest
    test_output = classifier(X_test)
  File "/home/lgpu0062/.conda/envs/dl/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lgpu0062/DeepLearningUvA/Assignment 1/code/convnet_pytorch.py", line 128, in forward
    out = layer(out)
  File "/home/lgpu0062/.conda/envs/dl/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lgpu0062/.conda/envs/dl/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 343, in forward
    return self.conv2d_forward(input, self.weight)
  File "/home/lgpu0062/.conda/envs/dl/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 340, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA out of memory. Tried to allocate 64.00 MiB (GPU 0; 10.92 GiB total capacity; 10.22 GiB already allocated; 21.50 MiB free; 138.50 MiB cached)
srun: error: r31n5: task 0: Exited with exit code 1
